### PR TITLE
Turn into monorepo

### PR DESCRIPTION
**Pull request by cmdcolin**
Changes the repo into a monorepo by splitting into 'app' and 'lib' directories

The app is now a `vite` app instead of `create-react-app`, which is a bit more lightweight

Can run `yarn dev` in the app dir and it will use the library in the lib directory. It does not automatically build what is in the lib directory, so if you make changes in the lib directory, you should re-run yarn build or run e.g. yarn build:esm --watch for a continuous watcher

### CODE REVIEW

**Comment by cmdcolin** [comment]
this PR is targetted to your make_component branch

It also removed the rollup script for now, but I can revive this if you are interested in having ability to include the seqpanel via a simple script tag, instead of/in addition to,  install from npm ability

**Comment by cmdcolin** [comment]
note: the readme says @gmod/generic-sequence-panel, but you would want to rename the "name" field in lib/package.json to "@gmod/generic-sequence-panel" to make it publish to that name, currently would just be generic-sequence-panel without the @gmod namespace

**Comment by cmdcolin** [comment]
essentially, after this PR is added, you can use `yarn publish` in the lib folder to publish to npm

**Comment by scottcain** [comment]
OK, that is A LOT. I'm going to merge, add the @gmod and do some testing.

**Comment by cmdcolin** [comment]
yes, it is indeed a large pr and just goes on to show that everything with developing libraries can be weird. there may be ways that could be simpler, but this should be ok. possibly we could remove the separation between lib and app, i read about possibly some ways of doing that

**Pull request merged**
